# Generated by Django 4.1 on 2023-07-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the drink', max_length=50)),
                ('description', models.TextField(help_text='A Description of the drink')),
                ('price', models.PositiveBigIntegerField(help_text='Price of the drink.')),
                ('quantity', models.PositiveIntegerField(choices=[(12, '12 OZ'), (20, '20 OZ')], help_text='Quantity of the dirnk in ounces.')),
                ('coffee_type', models.CharField(help_text='Type of coffee', max_length=20)),
                ('img', models.URLField(help_text='A url to the images', max_length=250)),
                ('hotness_type', models.CharField(choices=[('w', 'warm'), ('c', 'cold')], max_length=1)),
            ],
        ),
    ]
